SELECT * FROM products;


SELECT
	AVG(UNIT_PRICE) AS MEDIA,
	CEILING(AVG(UNIT_PRICE)),
	FLOOR(AVG(UNIT_PRICE)),
	ROUND(CAST(AVG(UNIT_PRICE) AS numeric), 2),
	trunc(CAST(AVG(UNIT_PRICE) AS numeric), 2)
FROM PRODUCTS;

